# eth 的 api
api: "KMF22IVKM1W6ZN4Q59VCV3KJ6WWURQN636"
# 需要监控的地址，列表形式支持多个
address: {
  "b1主账户": ""
}
# 钉钉 bot 的 api
botApi: "https://oapi.dingtalk.com/robot/send/?access_token="
# 钉钉 bot 的 key
botKey: "23ba4aa1ecbb50de8642c0d1fb406b3289da3bb33e2be0d008a3b08ff50731db"
# 获取频率，间隔多少秒请求一次
num: 10